{% set name = "pagerduty" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pagerduty-{{ version }}.tar.gz
  sha256: 84dfba74f68142c4a71c88af4858f1eb8671e7bc564bc133ac41c59daa7b54f8

build:
  entry_points:
    - pagerduty = pagerduty.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv_build
    - pip
  run:
    - python >={{ python_min }}
    - httpx

test:
  imports:
    - pagerduty
  commands:
    - pip check
    - pagerduty --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PagerDuty/python-pagerduty
  summary: Clients for PagerDuty's Public APIs
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PagerDuty/python-pagerduty
  doc_url: https://pagerduty.github.io/python-pagerduty/user_guide.html

extra:
  recipe-maintainers:
    - xylar
