{% set name = "pagerduty" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pagerduty-{{ version }}.tar.gz
  sha256: 36e0608228526f0dacd6ae16402259a91e11d3d7fa357f37ddbafbf8850d5e1f

build:
  entry_points:
    - pagerduty = pagerduty.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - certifi
    - requests
    - urllib3

test:
  imports:
    - pagerduty
  commands:
    - pip check
    - pagerduty --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PagerDuty/python-pagerduty
  summary: Clients for PagerDuty's Public APIs
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PagerDuty/python-pagerduty
  doc_url: https://pagerduty.github.io/python-pagerduty/user_guide.html

extra:
  recipe-maintainers:
    - xylar
